Rename package to npmPackage
package is a reserved word in javascript:

» ./bin/npm-proxy -c localhost:5984

node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
SyntaxError: In /Users/gregg/npm-proxy/lib/server.coffee, reserved word "package" on line 17
    at SyntaxError (unknown source)
    at Lexer.error (/Users/gregg/npm-proxy/node_modules/coffee-script/lib/coffee-script/lexer.js:686:13)
    at Lexer.identifierToken (/Users/gregg/npm-proxy/node_modules/coffee-script/lib/coffee-script/lexer.js:88:16)
    at Lexer.tokenize (/Users/gregg/npm-proxy/node_modules/coffee-script/lib/coffee-script/lexer.js:35:19)
    at /Users/gregg/npm-proxy/node_modules/coffee-script/lib/coffee-script/coffee-script.js:43:32
    at Object..coffee (/Users/gregg/npm-proxy/node_modules/coffee-script/lib/coffee-script/coffee-script.js:19:17)
    at Module.load (module.js:348:31)
    at Function._load (module.js:308:12)
    at Module.require (module.js:354:17)
    at require (module.js:370:17)